package pkg

const (
	NB_BASIC_TITANS   = 10
	NB_SPECIAL_TITANS = 6
	NB_TITANS         = NB_BASIC_TITANS + NB_SPECIAL_TITANS

	NB_VILLAGERS = 50
	NB_SOLDIERS  = 0
	NB_HUMANS    = NB_VILLAGERS + NB_SOLDIERS

	NB_AGENTS = NB_TITANS + NB_HUMANS

	EREN_LIFE           = 100
	MIKASA_LIFE         = 100
	VILLAGER_LIFE       = 100
	SOLDIER_LIFE        = 100
	BASIC_TITAN_LIFE    = 100
	COLOSSAL_TITAN_LIFE = 100
	ARMORED_TITAN_LIFE  = 100
	FEMININ_TITAN_LIFE  = 100
	JAW_TITAN_LIFE      = 100
	BEAST_TITAN_LIFE    = 100

	GRASS_LIFE       = 100000000000000
	WALL_LIFE        = 300
	BIG_HOUSE_LIFE   = 150
	SMALL_HOUSE_LIFE = 100
	DUNGEON_LIFE     = 500
	FIELD_LIFE       = 200
)
